language: node_js
node_js: '10'

jobs:
  include:
    - stage: test
      addons:
        firefox: 'latest-esr'
      before_script:
        - ./tasks/wiredeps
      script:
        - COVERAGE=1 TEST_BROWSERS=Firefox,PhantomJS xvfb-run npm run all
        - npx codecov
    - stage: update integration test
      script: './tasks/stages/update-integration-test'
    - stage: update examples
      script: './tasks/stages/update-examples'
    - stage: update demo
      script: './tasks/stages/update-demo'
    - stage: update website
      script: './tasks/stages/update-website'

stages:
  - test
  - name: update integration test
    if: tag =~ ^v\d
  - name: update examples
    if: tag =~ ^v\d+\.\d+\.\d+$
  - name: update demo
    if: tag =~ ^v\d+\.\d+\.\d+$
  - name: update website
    if: tag =~ ^v\d+\.\d+\.\d+$