name: MERGE_MASTER_TO_DEVELOP
on:
  push:
    branches:
    - "master"

jobs:
  Merge_master_to_develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
        fetch-depth: 0
    - name: Merge master to develop and push
      run: |
        git config user.name '${{ secrets.BPMN_IO_USERNAME }}'
        git config user.email '${{ secrets.BPMN_IO_EMAIL }}'
        git merge -m 'Merge master to develop' --no-edit origin/master
        git push

    - name: Notify failure on Slack
      if: failure()
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: "Automatic merge of <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}> to <https://github.com/${{ github.repository }}/tree/develop|${{ github.repository }}#develop> failed."
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
